version: '3'
services:
  gakusyu-kun:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/gakusyu-kun/
      - public-data:/gakusyu-kun//public
      - tmp-data:/gakusyu-kun//tmp/sockets
      - log-data:/var/log/nginx # 変更
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/gakusyu-kun/public
      - tmp-data:/gakusyu-kun/tmp
    ports:
      - 80:80
    depends_on:
      - gakusyu-kun

volumes:
  public-data:
  tmp-data:
    driver: local # 追加
  log-data:
    driver: local # 追加
  db-data:
